/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

package com.alibaba.himarket.service.impl;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.mockito.ArgumentMatchers.anyList;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.when;

import com.alibaba.himarket.core.security.ContextHolder;
import com.alibaba.himarket.dto.params.product.ProductSortBy;
import com.alibaba.himarket.dto.params.product.QueryProductParam;
import com.alibaba.himarket.dto.result.common.PageResult;
import com.alibaba.himarket.dto.result.product.ProductResult;
import com.alibaba.himarket.entity.Product;
import com.alibaba.himarket.repository.ApiDefinitionRepository;
import com.alibaba.himarket.repository.ConsumerRepository;
import com.alibaba.himarket.repository.ProductPublicationRepository;
import com.alibaba.himarket.repository.ProductRefRepository;
import com.alibaba.himarket.repository.ProductRepository;
import com.alibaba.himarket.repository.SubscriptionRepository;
import com.alibaba.himarket.service.AiRegistryService;
import com.alibaba.himarket.service.GatewayService;
import com.alibaba.himarket.service.McpToolService;
import com.alibaba.himarket.service.NacosService;
import com.alibaba.himarket.service.PortalService;
import com.alibaba.himarket.service.ProductCategoryService;
import com.alibaba.himarket.service.SkillService;
import com.alibaba.himarket.service.WorkerService;
import com.alibaba.himarket.support.enums.ProductType;
import com.alibaba.himarket.support.product.ProductFeature;
import com.alibaba.himarket.support.product.SkillConfig;
import com.alibaba.himarket.support.product.WorkerConfig;
import java.util.Collections;
import java.util.List;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.SpringBootConfiguration;
import org.springframework.boot.autoconfigure.EnableAutoConfiguration;
import org.springframework.boot.autoconfigure.domain.EntityScan;
import org.springframework.boot.test.autoconfigure.jdbc.AutoConfigureTestDatabase;
import org.springframework.boot.test.autoconfigure.orm.jpa.DataJpaTest;
import org.springframework.context.ApplicationEventPublisher;
import org.springframework.data.domain.PageRequest;
import org.springframework.data.jpa.repository.config.EnableJpaRepositories;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.test.context.ContextConfiguration;

@DataJpaTest(
        properties = {
            "spring.datasource.url=jdbc:h2:mem:product-sort;MODE=MySQL;DATABASE_TO_LOWER=TRUE;DB_CLOSE_DELAY=-1",
            "spring.jpa.defer-datasource-initialization=true",
            "spring.jpa.hibernate.ddl-auto=none",
            "spring.sql.init.mode=always",
            "spring.sql.init.schema-locations=classpath:db/h2/json-functions.sql",
            "debug=false"
        })
@AutoConfigureTestDatabase(replace = AutoConfigureTestDatabase.Replace.NONE)
@ContextConfiguration(classes = ProductDownloadCountSortRepositoryTest.RepositoryConfig.class)
public class ProductDownloadCountSortRepositoryTest {

    @Autowired private ProductRepository productRepository;

    @Autowired private JdbcTemplate jdbcTemplate;

    private ProductServiceImpl productService;

    @BeforeEach
    void setUp() {
        jdbcTemplate.execute(
                """
                CREATE TABLE IF NOT EXISTS product (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    product_id VARCHAR(64) NOT NULL,
                    admin_id VARCHAR(64),
                    name VARCHAR(64) NOT NULL,
                    type VARCHAR(64),
                    description VARCHAR(1000),
                    enable_consumer_auth BOOLEAN,
                    document CLOB,
                    icon VARCHAR(10000),
                    status VARCHAR(64),
                    auto_approve BOOLEAN,
                    feature JSON,
                    created_at TIMESTAMP(3),
                    updated_at TIMESTAMP(3),
                    CONSTRAINT uk_product_id UNIQUE (product_id)
                )
                """);
        productRepository.deleteAll();
        productService = newService(productRepository);
    }

    @Test
    void skillDownloadCountSortUsesDatabaseOrderAndPagination() {
        Product first = skillProduct("skill-1", 10L);
        Product second = skillProduct("skill-2", 10L);
        Product withoutCount = skillProduct("skill-without-count", null);
        Product withoutConfig =
                product(
                        "skill-without-config",
                        ProductType.AGENT_SKILL,
                        ProductFeature.builder().build());
        productRepository.saveAllAndFlush(List.of(first, second, withoutCount, withoutConfig));

        PageResult<ProductResult> firstPage = list(ProductType.AGENT_SKILL, 0, 2);
        PageResult<ProductResult> secondPage = list(ProductType.AGENT_SKILL, 1, 2);

        assertEquals(List.of("skill-2", "skill-1"), productIds(firstPage));
        assertEquals(
                List.of("skill-without-config", "skill-without-count"), productIds(secondPage));
        assertEquals(4, firstPage.getTotalElements());
    }

    @Test
    void workerDownloadCountSortUsesWorkerMetadata() {
        productRepository.saveAllAndFlush(
                List.of(workerProduct("worker-low", 3L), workerProduct("worker-high", 12L)));

        PageResult<ProductResult> result = list(ProductType.WORKER, 0, 10);

        assertEquals(List.of("worker-high", "worker-low"), productIds(result));
    }

    private PageResult<ProductResult> list(ProductType type, int page, int size) {
        QueryProductParam param = new QueryProductParam();
        param.setType(type);
        param.setSortBy(ProductSortBy.DOWNLOAD_COUNT);
        return productService.listProducts(param, PageRequest.of(page, size));
    }

    private Product skillProduct(String productId, Long downloadCount) {
        SkillConfig config = SkillConfig.builder().downloadCount(downloadCount).build();
        return product(
                productId,
                ProductType.AGENT_SKILL,
                ProductFeature.builder().skillConfig(config).build());
    }

    private Product workerProduct(String productId, long downloadCount) {
        WorkerConfig config = WorkerConfig.builder().downloadCount(downloadCount).build();
        return product(
                productId,
                ProductType.WORKER,
                ProductFeature.builder().workerConfig(config).build());
    }

    private Product product(String productId, ProductType type, ProductFeature feature) {
        return Product.builder()
                .productId(productId)
                .name(productId)
                .type(type)
                .feature(feature)
                .build();
    }

    private List<String> productIds(PageResult<ProductResult> result) {
        return result.getContent().stream().map(ProductResult::getProductId).toList();
    }

    private ProductServiceImpl newService(ProductRepository repository) {
        ContextHolder contextHolder = mock(ContextHolder.class);
        ProductRefRepository productRefRepository = mock(ProductRefRepository.class);
        ProductCategoryService productCategoryService = mock(ProductCategoryService.class);
        when(contextHolder.isAdministrator()).thenReturn(true);
        when(productRefRepository.findByProductIdIn(anyList())).thenReturn(Collections.emptyList());
        when(productCategoryService.listCategoriesForProducts(anyList()))
                .thenReturn(Collections.emptyMap());
        return new ProductServiceImpl(
                contextHolder,
                mock(PortalService.class),
                mock(GatewayService.class),
                repository,
                productRefRepository,
                mock(ApiDefinitionRepository.class),
                mock(ProductPublicationRepository.class),
                mock(SubscriptionRepository.class),
                mock(ConsumerRepository.class),
                mock(NacosService.class),
                productCategoryService,
                mock(McpToolService.class),
                mock(WorkerService.class),
                mock(SkillService.class),
                mock(AiRegistryService.class),
                mock(ApplicationEventPublisher.class));
    }

    @SpringBootConfiguration
    @EnableAutoConfiguration
    @EntityScan(basePackageClasses = Product.class)
    @EnableJpaRepositories(basePackageClasses = ProductRepository.class)
    static class RepositoryConfig {}
}
